import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sertantai_docs, SertantaiDocsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Enable gzip compression for better performance
  gzip: true,
  # Cache static assets for 1 year
  static_cache_control: "public, max-age=31536000"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: SertantaiDocs.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Production configuration for content integration
config :sertantai_docs,
  # Main app URL for cross-references in production
  main_app_url: {:system, "MAIN_APP_URL", "https://sertantai.com"},
  # Enable content caching in production
  cache_content: true,
  # File system monitoring (optional in production)
  file_monitoring: {:system, "ENABLE_FILE_MONITORING", "false"}

# Content synchronization settings
config :sertantai_docs, SertantaiDocs.Integration,
  sync_enabled: true,
  cache_ttl: 3600,  # 1 hour cache TTL
  max_content_size: 10_485_760  # 10MB max content size

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
