defmodule Sertantai.Repo.Migrations.AddCustomerUniqueConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:billing_customers, [:stripe_customer_id], unique: true)

    alter table(:billing_customers) do
      modify :email, :citext
    end

    create unique_index(:billing_customers, [:stripe_customer_id],
             name: "billing_customers_unique_stripe_customer_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:billing_customers, [:stripe_customer_id],
                     name: "billing_customers_unique_stripe_customer_id_index"
                   )

    alter table(:billing_customers) do
      modify :email, :text
    end

    drop_if_exists index(:billing_customers, [:stripe_customer_id])
  end
end
