defmodule :"Elixir.Sertantai.Repo.Migrations.Phase1: Add classification columns to UkLrt resource" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Columns already exist in database from data import
    # This migration only updates the Ash resource snapshot
    :ok
  end

  def down do
    # Columns should remain as they contain imported data
    :ok
  end
end
