defmodule Sertantai.Repo.Migrations.AddSubscriptionUniqueConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:billing_subscriptions, [:stripe_subscription_id], unique: true)

    create unique_index(:billing_subscriptions, [:stripe_subscription_id],
             name: "billing_subscriptions_unique_stripe_subscription_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:billing_subscriptions, [:stripe_subscription_id],
                     name: "billing_subscriptions_unique_stripe_subscription_id_index"
                   )

    drop_if_exists index(:billing_subscriptions, [:stripe_subscription_id])
  end
end
