defmodule Sertantai.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Skip uk_lrt and organizations tables - they already exist
    # Only add missing columns to ai_conversation_sessions
    alter table(:ai_conversation_sessions) do
      add :last_activity_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
      add :session_timeout_minutes, :bigint, default: 30
      add :recovery_checkpoint, :map, default: %{}
      add :interruption_reason, :text
    end
  end

  def down do
    # Only reverse the ai_conversation_sessions changes
    alter table(:ai_conversation_sessions) do
      remove :interruption_reason
      remove :recovery_checkpoint
      remove :session_timeout_minutes
      remove :last_activity_at
    end
  end
end
