defmodule Sertantai.Repo.Migrations.AddSyncConfigs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sync_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :target_service, :text, null: false
      add :config_data, :map, null: false, default: %{}
      add :field_mapping, :map, null: false, default: %{}
      add :filters, :map, default: %{}
      add :schedule, :text
      add :is_active, :boolean, null: false, default: true
      add :last_sync_at, :utc_datetime
      add :sync_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:sync_configs)
  end
end
